-- Fix activity_logs table for TiDB compatibility
-- TiDB doesn't allow changing PRIMARY KEY constraints
-- Workaround: Manual ID generation in application code
-- No database changes needed - handled in includes/config.php
